spring.application.name=marblejar-backend

# =====================
# SERVER
# =====================
server.port=${SERVER_PORT:8080}

# =====================
# DATASOURCE
# =====================
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}

# =====================
# JWT
# =====================
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}

# =====================
# SECURITY
# =====================
spring.main.allow-bean-definition-overriding=true

# =====================
# FRONTEND
# =====================
frontend.url=${FRONTEND_URL:http://localhost:5173}

# =====================
# LOGGING
# =====================
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG

# =====================
# SWAGGER
# =====================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.defer-datasource-initialization=true
